# pyproject.toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TSPsolver"
version = "0.1.0"
description = "A Python library for solving the Traveling Salesperson Problem using various algorithms."
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
dependencies = [
    "numpy"
]

[tool.setuptools]
packages = ["tsp_solver", "tsp_solver.algorithms"]